version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: webrtc-vlm-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: webrtc-vlm-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./models:/app/models
    restart: always
    environment:
      # Pass the mode to the backend container
      MODE: ${MODE:-wasm}